### ISSUE TITLE
Restructure

### ISSUE THREAD

**Issue by Siclol** [Jaspero/git-status-board#1]
Board(s) page should always visible (except login and 404), and the menu button (in app.component) should open dialogs and perform actions:

- Edit/display should toggle `jgb-edit` class on `jgb-board`
- Settings opens a dialog for board settings,
- Members opens a dialog for members (this is currently 'settings' component, rename it to members)
- My profile opens a dialog for my profile,
- Logout logs you out

On jgb-board, widget button should open a dialog. We should store all panels in that dialog, so a user can select which panel he would like to add. In case the current board is full of panels, a new board is created and a panel is inserted in it.

**Comment by flauc** [comment]
I'm not sure what you mean by "widget button"

**Comment by flauc** [comment]
- [ ] I connected the panel dialog we need to style it. 
- [ ] Style members panel

**Comment by Siclol** [comment]
I will move style for individual panels into a separate issue, and mark it done here.
